trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- group: "uumpa devops"

steps:
- task: AzureCLI@2
  env:
    REGISTRY: "$(container_registry_name)"
    IMAGE: "$(container_registry_login_server)/gamal:$(Build.SourceVersion)"
    APPCONFIG: "$(appconfig_name)"
  inputs:
    azureSubscription: 'uumpa service connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $REGISTRY &&\
      docker build -t $IMAGE . &&\
      docker push $IMAGE &&\
      az appconfig kv set -y --name $APPCONFIG --key gamal-latest-image --value $IMAGE
